config/routes.rb
Rails.application.routes.draw do

  get 'transactions/show'
  get 'carts/show'
  namespace :admin do
    get 'orders/_admin_order'
    get 'orders/index'
  end
  devise_for :admins
  devise_for :users do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  root to: 'products#index'

  resources :products, only: [:index, :show]
  resources :categories, only: [:show]
  resource :cart, only: [:show] do
    put 'add/:product_id', to: 'carts#add', as: :add_to
    put 'remove/:product_id', to: 'carts#remove', as: :remove_from
    put 'remove_one/:product_id', to: 'carts#removeone', as: :remove_one
  end
  
  resources :transactions, only: [:new, :create] do
    get '/transaction/new' => 'transactions#new'
  end
  
  namespace :admin do
    root to: 'products#index'
    resources :products, only: [:index, :new, :create, :edit, :update, :destroy]
    resources :categories, only: [:index, :new, :create, :edit, :update, :destroy]
    resources :orders, only: [:index]

  end
  namespace :products do
    post 'csv_upload'
  end
  get '/admin/products/:id' => 'admin/products#destroy'
  get '/admin/categories/:id' => 'admin/categories#destroy'
  get '/cart/add/:product_id' => 'carts#add'
end

app/models/product.rb
class Product < ApplicationRecord

  enum status: { draft: 0, published: 1, archieved: 2 }
  mount_uploader :image, ImageUploader

  has_many :product_categories, dependent: :destroy
  has_many :categories, through: :product_categories

  has_many :orders
  has_many :users, through: :orders

end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < ApplicationController

  before_action :authenticate_admin!

  def index
    @products = Product.all

  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)
    if @product.save
      @category_array = params.dig(:product, :category_ids)
      @category_array.each do |cat|
        @category = Category.find(cat)
        @product.categories << @category
      end
      flash[:notice] = "Product added!"
      redirect_to admin_products_path
    else
      flash[:notice] = "Product can't be blank!"
      render 'admin/products/new'
    end
  end

  def edit
    @product = Product.find(params[:id])
  end

  def update
    @product = Product.find(params[:id])
    if @product.update(product_params)
      @product.product_categories.destroy_all
      @category_array = params.dig(:product, :category_ids)
      @category_array.each do |cat|
        @category = Category.find(cat)
        @product.categories << @category
      end
      flash[:notice] = "Product updated!"
      redirect_to admin_products_path
    else
      render :edit
    end
  end

  def destroy
    Product.destroy(params[:id])
    flash[:notice] = "Product removed!"
    redirect_to admin_products_path
  end

  def csv_upload
    data = params[:csv_file].read.split("\n")
    data.each do |line| 
      attribute = line.split(",").map(&:strip)
      Product.create title: attribute[0], description: attribute[1], stock: attribute[2]
    end
    redirect_to action: :index
  end 

  def delete_upload
    Product.image.destroy(params[:id])
  end


  private
    def set_product
      @product = Product.find(params[:id])
    end

    def generate_csv(products)
      products.map { |p| [p.title, p.description, p.created_at].join(',') }.join("\n")
    end
    
  
    def product_params
      pp = params.require(:product).permit(:name, :description, :price, :image)
      pp[:status] = params[:product][:status].to_i
      return pp
 end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Product.all
    respond_to do |format|
      format.html
      format.csv { send_data generate_csv(Product.all), file_name: 'products.csv'}
    end

  end

  def show
    @product = Product.find(params[:id])
  end
  
  def csv_upload
    data = params[:csv_file].read.split("\n")
    data.each do |line| 
      attribute = line.split(",").map(&:strip)
      Product.create title: attribute[0], description: attribute[1], stock: attribute[2]
    end
    redirect_to action: :index
  end 


  def generate_csv(products)
    products.map { |p| [p.name, p.description, p.created_at].join(',') }.join("\n")
  end

end

app/helpers/admin/products_helper.rb
module Admin::ProductsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/admin/products/_admin_product.html.slim
tr
  td #{ admin_product.name }
  td #{ admin_product.description }
  td #{ admin_product.price }
  td #{ admin_product.status }
  <td> <image src = "#{(admin_product.image)}"> </td>

  td = link_to 'Edit', edit_admin_product_path(admin_product)
  td = link_to 'Delete', admin_product_path(admin_product), method: :delete

app/views/admin/products/edit.html.slim
h1.jumbotron Edit Product

.container
  = simple_form_for [:admin, @product], class: "form-horizontal" do |f|
    = f.input :name
    = f.input :description
    = f.input :price
    = f.input :status
    / 'Change Product
    = f.label 'Upload new image'
    = f.file_field :image
    = f.association :categories, collection: Category.all, as: :check_boxes, include_hidden: false

    = f.button :submit
  = link_to 'Back to Product List', admin_products_path

app/views/admin/products/index.html.slim
h1.jumbotron Admin | Products

.container
  .d-flex.align-items-center.justify-content-between
  h1.tablename.justify-content-start
    | Products 
  = link_to 'Download CSV', products_path(format: :csv), class: "btn btn-secondary justify-content-end"

  .row
    = link_to 'Add Product', new_admin_product_path
    .col-12.card
      table.table
        thead
          th Name
          th Description
          th Price
          th Status
        tbody
        = render partial: "admin_product", collection: @products

  .d-flex.align-items-center.justify-content-between
  th Or you can upload CSV file
  = form_tag admin_products_path, multipart: true do
    div
      = file_field_tag :csv_file
    div
      = submit_tag :upload

app/views/admin/products/new.html.slim
h1.jumbotron Add a Product

.container
  = simple_form_for [:admin, @product], class: "form-horizontal" do |f|
    = f.input :name
    = f.input :description
    = f.input :price
    = f.label 'Status 1 for published and 2 for archieved'
    = f.input :status
    = f.association :categories, collection: Category.all, as: :check_boxes, include_hidden: false
    = f.label 'Upload product image'
    = f.file_field :image
    = f.button :submit

  = link_to 'Back to Product List', admin_products_path